{% set name = "ml-collections" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_collections-{{ version }}.tar.gz
  sha256: 00b11a1a339dd6c2d9b7f0daab47ab17e10e29ca1b2a656058605e2b7210897f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - absl-py
    - pyyaml
    - six
    - contextlib2

test:
  imports:
    - docs
    - ml_collections
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/ml_collections
  summary: ML Collections is a library of Python collections designed for ML usecases.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
